# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 418995ff91643cd61c6dc284f426058c6f1553e7c3120eaf435647aa8b1773f3832c5f97e76d62cc8ba1f790c812c508ff3c045195f213df4f7c3842d907d7f8

test:
  secret_key_base: db0594f724226d7b3ceeeaff42ab4530ca6d4e514fa4361f65f3fd93aba17dbee21130789e8be097f88644c0ed96c4b662df0d5fd67d8c3039ee0bb7db76dacf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
